apiVersion: v1
kind: Service
metadata:
  name: torch-pod-external-service-aesteva
  labels:
    app: torch-pod-external-service-aesteva
spec:
  selector:
    app: torch-pod-aesteva
  type: LoadBalancer
# loadBalancerIP: 104.197.53.186

 #loadBalancerSourceRanges:
 #- 204.14.232.0/21
 #- 202.95.77.0/2
  ports:
  - port: 1339
    targetPort: 8888
